import { Inter } from 'next/font/google';
import Head from 'next/head';
import { ReactNode } from 'react';
import "./globals.css";

const inter = Inter({ subsets: ['latin'] });

interface LayoutProps {
  children: ReactNode;
}

const RootLayout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>VK Clone</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={inter.className}>{children}</div>
    </>
  );
};

export default RootLayout;